server:  
  port: 8888
spring:  
  application:
    name: configserver  
  cloud:
    config:
      server:
        git:
          uri: https://github.com/atSistemas/cygnus-config

logging:  
  file: logs/${spring.application.name}.log
  level:
    com.netflix.discovery: 'OFF'
    org.springframework.cloud: 'DEBUG'
    com.atsistemas: 'DEBUG'  